---
- name: Download windows_exporter package
  win_get_url:
    url: 'https://github.com/prometheus-community/windows_exporter/releases/download/v{{ _windows_exporter_version }}/windows_exporter-{{ _windows_exporter_version }}-{{ win_arch }}.msi'
    dest: '%USERPROFILE%\Downloads'
    checksum: "{{ windows_exporter_checksum }}"
    checksum_algorithm: sha256
  register: _download_installer
  until: _download_installer is succeeded
  retries: 5
  delay: 2

- name: Install windows_exporter package
  win_shell: |
    'msiexec /i windows_exporter-{{ _windows_exporter_version }}-{{ win_arch }}.msi ENABLED_COLLECTORS="ad,adfs,cache,cpu,cpu_info,cs,container,dfsr,dhcp,dns,fsrmquota,iis,logical_disk,logon,memory,msmq,mssql,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,process,remote_fx,service,tcp,time,vmware" TEXTFILE_DIR="C:\custom_metrics" LISTEN_PORT="9115"'
  args:
    chdir: '%USERPROFILE%\Downloads'
  register: _installed_exporter

