---
- name: Download windows_exporter package
  win_get_url:
    url: 'https://github.com/prometheus-community/windows_exporter/releases/download/v{{ _windows_exporter_version }}/windows_exporter-{{ _windows_exporter_version }}-{{ _win_arch }}.msi'
    dest: "{{ _windows_exporter_download_dir }}"
    checksum: "{{ __windows_exporter_checksum }}"
    checksum_algorithm: sha256
  register: _download_installer
  until: _download_installer is succeeded
  retries: 5
  delay: 2
  when: _windows_exporter_msi_local_dir | length == 0

- block:
  - name: Copy local msi installer to remote host
    win_copy:
      src: '{{ _windows_exporter_msi_local_dir }}/windows_exporter*'
      dest: "{{ _windows_exporter_download_dir }}"
    register: __windows_exporter_copied
  - name: Get windows_exporter version
    win_file_version:
      path: '{{ __windows_exporter_copied.dest }}'
    changed_when: false
    register: __windows_exporter_current_version_output
  - name: Set windows_exporter version
    set_fact:
      _windows_exporter_version: '{{__windows_exporter_current_version_output.file_major_part}}.{{__windows_exporter_current_version_output.file_minor_part}}.{{__windows_exporter_current_version_output.file_private_part}}'
  when: _windows_exporter_msi_local_dir | length > 0

- name: Install windows_exporter package
  win_command: 'msiexec /i windows_exporter-{{ _windows_exporter_version }}-{{ _win_arch }}.msi ENABLED_COLLECTORS="ad,adfs,cache,cpu,cpu_info,cs,container,dfsr,dhcp,dns,fsrmquota,iis,logical_disk,logon,memory,msmq,mssql,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,process,remote_fx,service,tcp,time,vmware" TEXTFILE_DIR="C:\custom_metrics" LISTEN_PORT="9115"'
  args:
    chdir: "{{ _windows_exporter_download_dir }}"
  register: _installed_exporter
